config/routes.rb
Peeramid::Application.routes.draw do

  resources :terms

  resources :courses do
    resources :sections do
      resources :lessons do
        member { get :start}
      end
    end
  end

  devise_for :users

  resources :users do
    resources :progressions do
      member { get :mark_completed}
    end
  end

  authenticated :user do
    root "courses#index", as: :authenticated_root
  end

  root 'pages#home'

  get 'help' =>  'pages#help'

end

app/models/term.rb
class Term < ActiveRecord::Base
end

app/controllers/terms_controller.rb
class TermsController < ApplicationController
  before_action :set_term, only: [:show, :edit, :update, :destroy]

  # GET /terms
  # GET /terms.json
  def index
    @terms = Term.all
  end

  # GET /terms/1
  # GET /terms/1.json
  def show
  end

  # GET /terms/new
  def new
    @term = Term.new
  end

  # GET /terms/1/edit
  def edit
  end

  # POST /terms
  # POST /terms.json
  def create
    @term = Term.new(term_params)

    respond_to do |format|
      if @term.save
        format.html { redirect_to @term, notice: 'Term was successfully created.' }
        format.json { render action: 'show', status: :created, location: @term }
      else
        format.html { render action: 'new' }
        format.json { render json: @term.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /terms/1
  # PATCH/PUT /terms/1.json
  def update
    respond_to do |format|
      if @term.update(term_params)
        format.html { redirect_to @term, notice: 'Term was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @term.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /terms/1
  # DELETE /terms/1.json
  def destroy
    @term.destroy
    respond_to do |format|
      format.html { redirect_to terms_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_term
      @term = Term.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def term_params
      params.require(:term).permit(:name, :content, :link)
    end
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/views/terms/_form.html.haml
= form_for @term do |f|
  - if @term.errors.any?
    #error_explanation
      %h2= "#{pluralize(@term.errors.count, "error")} prohibited this term from being saved:"
      %ul
        - @term.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :content
    = f.text_area :content
  .field
    = f.label :link
    = f.text_field :link
  .actions
    = f.submit 'Save'

app/views/terms/edit.html.haml
%h1 Editing term

= render 'form'

= link_to 'Show', @term
\|
= link_to 'Back', terms_path

app/views/terms/index.html.haml
%h1 Listing terms

%table
  %tr
    %th Name
    %th Content
    %th Link
    %th
    %th
    %th

  - @terms.each do |term|
    %tr
      %td= term.name
      %td= term.content
      %td= term.link
      %td= link_to 'Show', term
      %td= link_to 'Edit', edit_term_path(term)
      %td= link_to 'Destroy', term, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Term', new_term_path

app/views/terms/new.html.haml
%h1 New term

= render 'form'

= link_to 'Back', terms_path

app/views/terms/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @term.name
%p
  %b Content:
  = @term.content
%p
  %b Link:
  = @term.link

= link_to 'Edit', edit_term_path(@term)
\|
= link_to 'Back', terms_path