config/routes.rb
Peeramid::Application.routes.draw do

  resources :terms

  resources :courses do
    resources :sections do
      resources :lessons do
        member { get :start}
      end
    end
  end

  devise_for :users

  resources :users do
    resources :progressions do
      member { get :mark_completed}
    end
  end

  authenticated :user do
    root "courses#index", as: :authenticated_root
  end

  root 'pages#home'

  get 'help' =>  'pages#help'

end

app/models/progression.rb
class Progression < ActiveRecord::Base
	belongs_to :user
	belongs_to :progressable, :polymorphic => true


	def complete
		self.is_completed = true
		self.completed_at = Time.now
		self.save
	end

	def mark_approved
		self.is_approved = true
		self.approved_at = Time.now
		self.save
	end
end

app/controllers/progressions_controller.rb
class ProgressionsController < ApplicationController
  before_filter :user
  before_action :set_progression, only: [:show, :edit, :update, :destroy]




  # GET /progressions
  # GET /progressions.json
  def index
    @progressions = @user.progressions
  end

  def new
    @progression = Progression.new
  end

  def create
    @progression = @user.progressions.new(params[:progression])

    respond_to do |format|
      if @progression.save
        format.html { redirect_to [@user, @progression], notice: 'Progression was successfully created.' }
        format.json { render action: 'show', status: :created, location: [@user, @progression] }
      else
        format.html { render action: 'new' }
        format.json { render json: @progression.errors, status: :unprocessable_entity }
      end
    end
  end



  def destroy
    @progression.destroy
    respond_to do |format|
      format.html { redirect_to progressions_url }
      format.json { head :no_content }
    end
  end

  def user
    @user ||= User.find(params[:user_id])
  end

  def mark_completed
    @progression = Progression.find(params[:id])
    @progression.complete
    redirect_to request.referer, notice: "You've completed this lesson, we're telling your boss!"
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_progression
      @progression = Progression.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def progression_params
      params.require(:progression).permit(:name, :progressable_id, :progressable_type, :is_completed, :is_approved)
    end
end

app/helpers/progressions_helper.rb
module ProgressionsHelper
end

app/views/progressions/_form.html.haml
= form_for @progression do |f|
  - if @progression.errors.any?
    #error_explanation
      %h2= "#{pluralize(@progression.errors.count, "error")} prohibited this progression from being saved:"
      %ul
        - @progression.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :progressable_id
    = f.number_field :progressable_id
  .field
    = f.label :progressable_type
    = f.text_field :progressable_type
  .field
    = f.label :is_completed
    = f.check_box :is_completed
  .field
    = f.label :is_approved
    = f.check_box :is_approved
  .actions
    = f.submit 'Save'

app/views/progressions/edit.html.haml
%h1 Editing progression

= render 'form'

= link_to 'Show', @progression
\|
= link_to 'Back', progressions_path

app/views/progressions/index.html.haml
%h1 Listing progressions

%table
  %tr
    %th Name
    %th Progressable
    %th Progressable type
    %th Is completed
    %th Is approved
    %th
    %th
    %th

  - @progressions.each do |progression|
    %tr
      %td= progression.name
      %td= progression.progressable_id
      %td= progression.progressable_type
      %td= progression.is_completed
      %td= progression.is_approved
      %td= link_to 'Show', progression
      %td= link_to 'Edit', edit_progression_path(progression)
      %td= link_to 'Destroy', progression, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Progression', new_progression_path

app/views/progressions/new.html.haml
%h1 New progression

= render 'form'

= link_to 'Back', progressions_path

app/views/progressions/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @progression.name
%p
  %b Progressable:
  = @progression.progressable_id
%p
  %b Progressable type:
  = @progression.progressable_type
%p
  %b Is completed:
  = @progression.is_completed
%p
  %b Is approved:
  = @progression.is_approved

= link_to 'Edit', edit_progression_path(@progression)
\|
= link_to 'Back', progressions_path