config/routes.rb
Peeramid::Application.routes.draw do

  resources :terms

  resources :courses do
    resources :sections do
      resources :lessons do
        member { get :start}
      end
    end
  end

  devise_for :users

  resources :users do
    resources :progressions do
      member { get :mark_completed}
    end
  end

  authenticated :user do
    root "courses#index", as: :authenticated_root
  end

  root 'pages#home'

  get 'help' =>  'pages#help'

end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
	belongs_to :section
	belongs_to :course

	has_many :progressions, :as => :progressable
	has_many :users, :through => :progressions

	validates :name, presence: true






end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_section
  before_action :set_lesson, only: [:start, :show, :edit, :update, :destroy]

  # GET /lessons
  # GET /lessons.json
  def index
    @lessons = @section.lessons.includes(:progressions)
  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show
    @progress = @lesson.progressions.find_by(:user => current_user)
  end

  # GET /lessons/new
  def new
    @lesson = course.section.lessons.build
  end

  # GET /lessons/1/edit
  def edit
  end

  # POST /lessons
  # POST /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to course_section_lessons_path(@course, @section), notice: 'Lesson was successfully created.' }
        format.json { render action: 'show', status: :created, location: @lesson }
      else
        format.html { render action: 'new' }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1
  # PATCH/PUT /lessons/1.json
  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to @course, notice: 'Lesson was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to lessons_url }
      format.json { head :no_content }
    end
  end


  def start
    Progression.create([:user => current_user, :progressable => @lesson])
    redirect_to course_section_lesson_path(@course, @section, @lesson), notice: 'You have officially Started this Lesson'
  end



  private
    # Use callbacks to share common setup or constraints between actions.\
    def set_section
      @course = Course.find(params[:course_id])
      @section = @course.sections.find(params[:section_id])
    end

    def set_lesson
      @lesson = @section.lessons.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lesson_params
      params.require(:lesson).permit(:name, :description)
    end

end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_form.html.haml
= form_for [@course, @section, @lesson] do |f|
  - if @lesson.errors.any?
    #error_explanation
      %h2= "#{pluralize(@lesson.errors.count, "error")} prohibited this lesson from being saved:"
      %ul
        - @lesson.errors.full_messages.each do |msg|
          %li= msg


  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .actions
    = f.submit 'Save'

app/views/lessons/edit.html.haml
%h1 Editing lesson

= render 'form'

app/views/lessons/index.html.haml
- @lessons.each do |l|
	%h1= link_to l.name, course_section_lesson_path(@course, @section, l)
	- if l.progressions.find_by(:user => current_user).is_completed
		%div{:id => [l.id, "completed"]}

.well
	= link_to @course.name, @course
	%br
	= link_to @section.name, course_section_path(@course, @section)

app/views/lessons/new.html.haml
%h1 New lesson

= render 'form'

= link_to 'Back', lessons_path

app/views/lessons/show.html.haml
.container
	.row
		.col-md-6.col-md-offset-3
			- if @progress
				.well{:id => [@lesson.id, "completed"]}
					= "Lesson started: " + @progress.created_at.strftime("%B %d %Y")
					%br
					- unless @progress.is_completed?
						= link_to "Mark Completed", mark_completed_user_progression_path(current_user.id, @progress)
					- else
						= "Lesson completed: " + @progress.completed_at.strftime("%B %d %Y")

			- else
				=link_to 'Start Lesson', start_course_section_lesson_path(@course, @section, @lesson)
			%br

			%h1= @lesson.name

			= RDiscount.new(@lesson.description).to_html.html_safe

			%br

			=link_to 'Edit This Lesson', edit_course_section_lesson_path(@course, @section, @lesson)