config/routes.rb
Peeramid::Application.routes.draw do

  resources :terms

  resources :courses do
    resources :sections do
      resources :lessons do
        member { get :start}
      end
    end
  end

  devise_for :users

  resources :users do
    resources :progressions do
      member { get :mark_completed}
    end
  end

  authenticated :user do
    root "courses#index", as: :authenticated_root
  end

  root 'pages#home'

  get 'help' =>  'pages#help'

end

app/views/layouts/_footer.html.haml
.push
%footer
	<h4>Contact:  <a href="mailto:founders@juntoist.com">founders@juntoist.com</a></h4>
	%p &copy; Juntoist 2013

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
  <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/courses">PEERAMID</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <%- if user_signed_in? %>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sign Out<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
                <li><%= link_to "Edit Info", edit_user_registration_path %>
          <% else %>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sign In<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Sign In", new_user_session_path %></li>
                <li><a href="#">Sign In with Facebook</a></li>
          <% end %>

            <li class="divider"></li>
            <li><%= link_to "Help", help_path%></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>
<!--- /.containter -->

app/views/layouts/application.html.haml
!!! 5
%html{"lang" => "en"}
	%head
	%title Peeramid
	= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
	= javascript_include_tag "application", "data-turbolinks-track" => true
	= csrf_meta_tags
	%meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}

	<link href='http://fonts.googleapis.com/css?family=Playfair+Display' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Lato:400,900' rel='stylesheet' type='text/css'>


%body
	.wrapper
		= render :partial => 'layouts/header'
		%div{:class => request.fullpath == "/" ? 'home' : 'container' }
			- flash.each do |name, msg|
				= content_tag(:div, msg, class: "alert alert-#{name}")
			= yield
		= render :partial => 'layouts/footer'